### ISSUE TITLE
No scheduled commands are ready to run

### ISSUE THREAD

**Issue by goemaeret** [spatie/uptime-monitor-app#1]
Hi,

When executing the `schedule:run` command I'm getting the following output in my terminal:
`No scheduled commands are ready to run`

Nothing seems to happen, I've added a site through the `monitor:create` command and after running the `schedule:run` command it still says "Not yet checked" when retrieving a list with the `monitor:list` command.

Am I missing something here?

Thx in advance,
Thomas

**Comment by freekmurze** [comment]
Hi,

thanks for bringing this to my attention. I've updated `Kernel.php` with the right scheduling.

Please replace `app/Console/Kernel.php` in your project by [this file](https://github.com/spatie/uptime-monitor-app/blob/master/laravel/app/Console/Kernel.php) to fix the problem.
