### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by benyanke** [spatie/uptime-monitor-app#13]
Have you considered setting up a docker image? Dockerhub can provide free builds, so it would only need a link to the repo and a Dockerfile committed to the repo.

I'd be happy to work on the Dockerfile if you'd be interested - I could write my own, but it's never as smooth as if it's in the same repo as the code, autobuilding on new code pushes.

Love all your packages - I use many at work!

**Comment by freekmurze** [comment]
I'd accept a PR that adds a Dockerfile + instructions to the readme on how to use this app with Docker. 👍
