### ISSUE TITLE
Undefined variable: certificateFound

### ISSUE THREAD

**Issue by idleberg** [spatie/uptime-monitor-app#16]
As of recently, when I run `laravel/artisan monitor:list`, the following error pops up.

```
Healthy monitors
================

In Healthy.php line 35:

  compact(): Undefined variable: certificateFound
```

PHP 7.3.2

**Comment by freekmurze** [comment]
Because I'm not using this application anymore i've decided to abandon it. Please use the spatie/laravel-uptime-monitor package directly.
