### ISSUE TITLE
Install uptime-monitor-app for Laravel 5.3

### ISSUE THREAD

**Issue by fahadkhan1740** [spatie/uptime-monitor-app#7]
I am trying to install `1.0` version but when I add `spatie/laravel-uptime-monitor` in my composer and do `composer install` nothing really happens. When I just use `*`, it installs `v2` which in not compatible with `5.3`. Do I need to add some prefix or suffix for `1.0`? I tried the following part 

`"spatie/laravel-uptime-monitor" : "1.*"`
`"spatie/laravel-uptime-monitor" : "^1.0"`

Both didn't install anything.

**Comment by freekmurze** [comment]
Composer will pick the right version for you if you run `composer require spatie/laravel-uptime-monitor` on the commandline.
