### ISSUE TITLE
Question: what is the difference?

### ISSUE THREAD

**Issue by BorislavSabev** [spatie/uptime-monitor-app#9]
Hello.

What is the exact difference between the app in this repository and the one in [https://github.com/spatie/laravel-uptime-monitor](spatie/laravel-uptime-monitor)

Cheers,
    Borkata

**Comment by sebastiandedeyne** [comment]
The uptime monitor is built to check the health of your websites, for example, "is "https://borislavsabev.com up?"

The server monitor is built to check the status of your server processes, for example "is MySQL running?", or "is my disk almost full?"

**Comment by BorislavSabev** [comment]
Hey @sebastiandedeyne  thanks. 
My point was that this is not clear from the documentation.

For you "the uptime monitor" is spatie/uptime-monitor-app, right?
And "the server" is spatie/laravel-uptime-monitor, right?


I'll submit a PR against both README.md's once it is clear for me.
Thanks.

**Comment by sebastiandedeyne** [comment]
Oh sorry misunderstood!

The other repository is a library that can be installed in an existing Laravel app to monitor uptime from that application.

This repository is a full application that uses the library, so it's ready to install on your server without any extra setup.
